"""Added indexes to various columns.

Revision ID: 257098e11494
Revises: dd7437393d93
Create Date: 2020-05-28 22:24:42.091870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257098e11494'
down_revision = 'dd7437393d93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_block_files_name'), 'block_files', ['name'], unique=False)
    op.create_index(op.f('ix_directories_name'), 'directories', ['name'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_constraint('users_username_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_directories_name'), table_name='directories')
    op.drop_index(op.f('ix_block_files_name'), table_name='block_files')
    # ### end Alembic commands ###
