"""empty message

Revision ID: dd7437393d93
Revises: c0b3ee18671a
Create Date: 2020-05-06 17:47:57.518791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7437393d93'
down_revision = 'c0b3ee18671a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('directories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['directories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('block_files', sa.Column('directory_id', sa.Integer(), nullable=True))
    op.add_column('block_files', sa.Column('name', sa.String(length=255), nullable=True))
    op.drop_constraint('block_files_project_id_fkey', 'block_files', type_='foreignkey')
    op.create_foreign_key(None, 'block_files', 'directories', ['directory_id'], ['id'])
    op.drop_column('block_files', 'path')
    op.drop_column('block_files', 'project_id')
    op.add_column('projects', sa.Column('root_directory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'directories', ['root_directory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'root_directory_id')
    op.add_column('block_files', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('block_files', sa.Column('path', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'block_files', type_='foreignkey')
    op.create_foreign_key('block_files_project_id_fkey', 'block_files', 'projects', ['project_id'], ['id'])
    op.drop_column('block_files', 'name')
    op.drop_column('block_files', 'directory_id')
    op.drop_table('directories')
    # ### end Alembic commands ###
